package transliter

import (
	"encoding/json"
	"fmt"
)

// ModelID is a stable application-facing model identifier.
type ModelID string

// OptionProfile selects a model-specific generation configuration.
type OptionProfile string

const (
	ProfileOfficial      OptionProfile = "official"
	ProfileDeterministic OptionProfile = "deterministic"
)

// OptionProvenance describes where generation values came from.
type OptionProvenance string

const (
	ProvenanceOfficialRecommendation OptionProvenance = "official_recommendation"
	ProvenanceOfficialExample        OptionProvenance = "official_example"
	ProvenanceProjectExperimental    OptionProvenance = "project_experimental"
)

// GenerationOptions is backend-neutral. Nil pointer fields are intentionally
// unspecified and must be omitted by an inference adapter.
type GenerationOptions struct {
	Temperature       *float64
	TopP              *float64
	TopK              *int
	RepetitionPenalty *float64
	DoSample          *bool
	MaxOutputTokens   int
	Stop              []string
	Provenance        OptionProvenance
}

// Descriptor contains model discovery metadata suitable for a CLI or API.
type Descriptor struct {
	ID             ModelID
	Family         string
	Parameters     string
	Repository     string
	GGUFRepository string
}

// Capabilities declares model input constraints without starting inference.
type Capabilities struct {
	PromptKinds            []PromptKind
	RequiresSourceLanguage bool
	StructuredUserContent  bool
	MaxInputTokens         int
}

// Role is a chat message role.
type Role string

const (
	RoleUser Role = "user"
)

// ContentPart is a structured user-content item. TranslateGemma uses one text
// part with source and target locale codes.
type ContentPart struct {
	Type               string `json:"type"`
	Text               string `json:"text"`
	SourceLanguageCode string `json:"source_lang_code,omitempty"`
	TargetLanguageCode string `json:"target_lang_code,omitempty"`
}

// Message supports either plain string content or structured content parts.
// Exactly one representation should be populated.
type Message struct {
	Role  Role
	Text  string
	Parts []ContentPart
}

// MarshalJSON produces the chat-completion content shape required by the
// selected model.
func (message Message) MarshalJSON() ([]byte, error) {
	if message.Role == "" {
		return nil, fmt.Errorf("message role must not be empty")
	}
	if message.Text != "" && len(message.Parts) > 0 {
		return nil, fmt.Errorf("message cannot contain both text and parts")
	}
	if len(message.Parts) > 0 {
		return json.Marshal(struct {
			Role    Role          `json:"role"`
			Content []ContentPart `json:"content"`
		}{Role: message.Role, Content: message.Parts})
	}
	return json.Marshal(struct {
		Role    Role   `json:"role"`
		Content string `json:"content"`
	}{Role: message.Role, Content: message.Text})
}

// ModelInput is the backend-neutral chat input generated by a Model.
type ModelInput struct {
	Messages []Message `json:"messages"`
}

// Model is the extension point implemented by every model-specific package.
type Model interface {
	Descriptor() Descriptor
	Capabilities() Capabilities
	SupportsLanguage(Language) bool
	BuildInput(TranslationRequest) (ModelInput, error)
	Options(OptionProfile) (GenerationOptions, error)
}

// Pointer returns a pointer to value for optional generation fields.
func Pointer[T any](value T) *T {
	return &value
}
